version: '3.8'

services:
  backend:
    build: ./backend
    container_name: blog-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - blog-network

  frontend:
    build: ./frontend
    container_name: blog-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge